import 'package:telegram/models/user_model.dart';

List<UserModel> userData = [
  UserModel(
    id: 1,
    name: "Theresa Webb",
    phone: "+357898990343",
    image: "assets/users/user1.jpeg",
    bio: "I am a designer from microsoft",
    message: "Hello, how are you?",
    time: DateTime.now().hour,
  ),
  UserModel(
    id: 2,
    name: "Calvin Fores",
    phone: "+357898990343",
    image: "assets/users/user1.jpeg",
    bio: "I am a Frontend from microsoft",
    message: "Hello, will you stop ignoring me?",
    time: DateTime.now().minute,
  ),
  UserModel(
    id: 3,
    name: "Gregory Bell",
    phone: "+357898990343",
    image: "assets/users/user1.jpeg",
    bio: "I am a designer from microsoft",
    message: "Hello bro!, Come To my house",
    time: DateTime.now().minute,
  ),
  UserModel(
    id: 4,
    name: "Soham Henry",
    phone: "+357898990343",
    image: "assets/users/user1.jpeg",
    bio: "I am a designer from microsoft",
    message: "Hello, Why did you do that?",
    time: DateTime.now().minute,
  ),
  UserModel(
    id: 5,
    name: "Mother",
    phone: "+357898990343",
    image: "assets/users/user1.jpeg",
    bio: "I am a designer from microsoft",
    message: "yes , of course come",
    time: DateTime.now().minute,
    sentBy: "me",
    unread: false,
  ),
  UserModel(
    id: 6,
    name: "Brother",
    phone: "+357898990343",
    image: "assets/users/user1.jpeg",
    bio: "I am a designer from microsoft",
    message: "Ok, I will come",
    time: DateTime.now().minute,
    sentBy: "me",
    unread: false,
  ),
];
